[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.zip", "php82Extensions.fileinfo", "php82Extensions.gd"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-gd",
  "php artisan key:generate",
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port 8000"
